GET http://localhost:8000/api/reviews
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTM5NTM2NzIsImV4cCI6MTcxMzk5Njg3Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibWFyay5icm91Z2g4NUBnbWFpbC5jb20ifQ.G3ViyjyN8FWXz458MC-fxnI-If0TZTjmqU5brzfrg30Z0hibloI_-lidTxJDoFAZUSw2mrdt_Of_gKw8DNRSP-YE0s4xNYRSSIfReOg5KUwNjlZHF79oDe6gLveFSdJAbR3G_wwHmdzQlthImu0UWFgbWR9d6nxcy49Po9NzBKIrMdk5UcTRyrTamjS02kj3CL4GeOlhCDyPXe9UDCK3p6_5haPpKb2Vus_g_aFtRxvFZFCfdZ3l4RuOHsCjxUVqJE7j415ao0eopWkjpuTDbKqiaUpmRq4hvW1V-0QFHptXAq-X54wB7wNT83faf4_VA7tJ0tIWAYWtM4MqjiSGbg
Accept: application/json